### ISSUE TITLE
The MCC of R U R' is more than the MCC of R U2 R' 

### ISSUE THREAD

**Issue by nbwzx** [trangium/trangium.github.io#1]
The Move count Coefficient of R U R' is 3.4 and the Move count Coefficient of R U2 R' is 3.3 with the default setting.
But in my opinion, we would always execute R U R' faster than R U2 R'.

**Comment by trangium** [comment]
This occurs because the MCC considers the time required to reposition your index finger for the U larger than the time required to do a half turn vs a quarter turn. Your index finger has only the time of a single R move to reposition to do a pinch or push, which the MCC considers to be not enough time (with the default settings). If you don't want this to happen, lower the overwork penalty below 2.2.

**Comment by nbwzx** [comment]
Okey, I understand, thanks for your answer.
